version: '1.0.0'
volumes:
  db-data:
    name: db-volume
services:
  auth-service:
    container_name: auth-service
    image: auth-service_notes
    env_file:
      - services.env
    build: 
      context: ./auth-service
    ports:
      - "7777:${API_PORT}"
    depends_on:
      - db-mongo
  notes-service:
    container_name: notes-service
    image: notes-service_notes
    env_file:
      - services.env
    build: 
      context: ./notes-service
    ports:
      - "8888:${API_PORT}"
    depends_on:
      - db-mongo
  app:
    hostname: localhost
    container_name: app
    image: angular-container
    build:
      context: ./app
    ports:
      - "80:80"
  db-mongo:
    hostname: localhost
    container_name: db-service
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/db/data